actors:
  mami:
    image_url: /images/actors/mami.jpg
    name: 御茶海マミ
    url: https://twitter.com/samami27
  aoharu:
    image_url: /images/actors/aoharu.jpg
    name: あおはる
    url: https://twitter.com/yokuwakan_nai
  qtaro:
    image_url: /images/actors/qtaro.jpg
    name: Ｑ太郎
    url: https://twitter.com/nantyaraidol
  alexa:
    image_url: /images/actors/alexa.jpg
    name: Alexa
    url: https://twitter.com/‪alexa99‬
  rotten:
    image_url: /images/actors/rotten.jpg
    name: ロットン瑠唯
    url: https://twitter.com/rotten_rui
  himeeeno:
    image_url: /images/actors/himeeeno.jpg
    name: 姫乃たま
    url: https://twitter.com/Himeeeno
  k_genda:
    image_url: /images/actors/k_genda.jpg
    name: 源田和樹
    url: https://twitter.com/K_Genda
  1ssiki2sssiki34:
    image_url: /images/actors/1ssiki2sssiki34.jpg
    name: 一色進
    url: https://twitter.com/1ssiki2sssiki34
  haruka:
    image_url: /images/actors/haruka.jpg
    name: DJタマキ
    url: https://twitter.com/tamakinodj
  uerin02142:
    image_url: /images/actors/uerin02142.jpg
    name: うえりん
    url: https://twitter.com/uerin02142
  pinkosyou_a:
    image_url: /images/actors/pinkosyou_a.jpg
    name: ぴんく和尚
    url: https://twitter.com/pinkosyou_a
  mandokoro:
    image_url: /images/actors/mandokoro.jpg
    name: 高野政所
    url: https://twitter.com/mandokoro
  nununu14sai:
    image_url: /images/actors/nununu14sai.jpg
    name: "null"
    url: https://twitter.com/nununu14sai
  rukatama:
    image_url: /images/actors/rukatama.jpg
    name: "ルカタマ"
    url: https://x.com/rukatamaki
  katahaba:
    image_url: /images/actors/katahaba.jpg
    name: 肩幅ヒロシ
    url: https://x.com/nandakonokata
  azusa:
    image_url: /images/actors/azusa.jpg
    name: 六條アズサ
    url: https://x.com/azusa_blog
  okaeri:
    image_url: /images/actors/okaeri.jpg
    name: オカエリ
    url: https://x.com/ni_n_p_
  nattyan:
    image_url: /images/actors/nattyan.jpg
    name: なっチャンホンポ
    url: https://x.com/NN0872
  mashiro:
    image_url: /images/actors/mashiro.jpg
    name: 真白ゆう
    url: https://x.com/blanche0u0
  hiyori:
    image_url: /images/actors/hiyori.jpg
    name: スナックひより
    url: https://x.com/snackhiyori
  yancya:
    image_url: /images/actors/yancya.jpg
    name: やんちゃ
    url: https://x.com/yancya
author: なんちゃらアイドル
description: https://listen.style/p/nantyaradio?I2Ls5ODl
description_long: なんちゃらアイドルのポッドキャスト。毎週金曜日 22:55 に更新
email: nantyara@upec.jp
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: なんちゃラジオ
itunes_podcast_url: https://itunes.apple.com/jp/podcast/id1333086389
spotify_podcast_url: https://open.spotify.com/show/7nD0bOrJS48FAh8tjDmaBm
keywords: idol
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: なんちゃラジオ
og_url: https://podcast.nantyara.com
